const ACTIONS = {
  FILM_SELECTED: 'FILM_SELECTED',
  FETCH_DATA_REQUEST: 'FETCH_DATA_REQUEST',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  SORT_BY_RATING: 'SORT_BY_RATING',
  SORT_BY_DATE:'SORT_BY_DATE',
  CLOSE_DESCRIPTION: 'CLOSE_DESCRIPTION',
  SET_SORT_FILTER: 'SET_SORT_FILTER',
};

const PATHS = {
  DEFAULT: '/',
  MOVIES: '/movies',
  MOVIE: '/description',
  NOTFOUND: '/page-not-found',
  RESTURLS: '*',
};

export { ACTIONS, PATHS };
